### ISSUE TITLE
[parsing?] ; 임시 처리

### ISSUE THREAD

**Issue by todoni** [alee-sohan-minishell/minishell#29]
; 기준으로 하나의 코드블럭이므로 처음에 스페이스바 제외하고 ;로 나눠서 각각이 순서대로 실행되게 해야함. 동시 실행 x 한번에 하나씩 순서대로. 
일단 1. ;로 split 하고 그 안에서 또 스페이스바로 split.
2. ;로 나눠진 만큼 반복문 돌면서 ft_exec_command 실행

**Comment by todoni** [comment]
*추후에 고려*
그리고 ;기준으로 나눠진 블록에서 또 나눌 때 pipe이면 pipe라고 알 수 있게 해야할 듯. pipe는 리스트로 연결 한다든가..
(pipe)나 ; 사이에 있는 문자열들은 이제 무조건 스페이스바로 나눠서 그 배열을 갖고 실행 시키면 됨. 
아마 리다이렉션도 (pipe) 자리에 들어가면 동일하게 적용 될 것 같은데 알아봐야함
                                         배열 [0]                         배열[1]                    배열[2]      -> 반복문으로 순서대로 실행  
                                        코드 블럭 ;                     코드 블럭 ;                코드 블럭 ; 
                            커맨드     ---->    커맨드
                           배열[0]    (pipe)   배열[0] 
                           배열[1]                  배열[1]
                           배열[2]                      .
                               .                            .
                               .                            .
                               .
이런식의 구조가 되지 않을까?

**Comment by guny524** [comment]
<img width="947" alt="Screen Shot 2022-05-28 at 4 53 15 PM" src="https://user-images.githubusercontent.com/43983919/170816265-e5109655-202a-43e8-aa41-d2c5f6dc6ffc.png">

; 세미콜론 처리하면 안 된다는 거 같아요
